name: Notify Repository URL at 7:00 AM Vietnam Time

on:
  schedule:
    - cron: '0 0 * * *' # Chạy vào 00:00 UTC (7:00 sáng Việt Nam)
  workflow_dispatch: # Cho phép chạy thủ công nếu cần

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Repository URL to Discord
        run: |
          # Lấy URL của repository từ GitHub Actions context
          REPO_URL="https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}"

          # Tạo thông báo gửi đến Discord
          MESSAGE="download tool:${{ github.event.repository.name }}\n"
          MESSAGE+="Repository URL: $REPO_URL"

          # Gửi thông tin qua webhook Discord
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{"content": "'"$MESSAGE"'"}' \
            "$HOOK_URL"
