name: Send GitHub Repos to Discord Hourly

on:
  schedule:
    - cron: '0 * * * *' # Chạy mỗi giờ vào phút thứ 0
  workflow_dispatch: # Cũng cho phép chạy thủ công nếu cần

jobs:
  send_repos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get repository list
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/users/ursenic/repos?per_page=100" \
            | jq -r '.[].html_url' > repos.txt
          echo "Repositories fetched:"
          cat repos.txt

      - name: Send to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          REPO_LIST=$(cat repos.txt | jq -Rs .) # Convert danh sách URL thành chuỗi JSON
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \"Free tool download:\n$REPO_LIST\"}" \
               $DISCORD_WEBHOOK_URL
